[package]
name = "cmajor-lang"
description = "Language tooling for Cmajor: lexing, parsing, and analysis."
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
insta = { version = "1.48.0", features = ["yaml"] }
indoc = { version = "2.0" }
serde = { version = "1", features = ["derive"] }
